<div class="col2-set">
    <div class="box">
        <div class="box-content">
            <div class="col-1">
                <h2><?php echo $this->__('Default Billing Address') ?></h2>
                <a class="edit" href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                </address>
            </div>
            <!--
            <div class="col-2">
                <h2><?php echo $this->__('Default Shipping Address') ?></h2>
                <a class="edit" href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit') ?></a>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                </address>
            </div>
            -->
        </div>
    </div>
</div>
<div>
    <a class="manage" href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
</div>
