<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1><?php echo $this->__('My Product Reviews') ?></h1>
</div>
<?php if( $this->getCollection() && $this->count()): ?>

    <ul class="accountlistheader">
        <li class="date"><?php echo $this->__('Date'); ?></li>
        <li class="productname"><?php echo $this->__('Product'); ?></li>
        <li class="review"><?php echo $this->__('Review'); ?></li>
        <li class="last">&nbsp;</li>
    </ul>
    <?php foreach ($this->getCollection() as $_review): ?>
    <ul class="accountlist">
        <li class="date"><span class="nobr"><?php echo $this->dateFormat($_review->getReviewCreatedAt()); ?></span></li>
        <li class="productname"><h2 class="product-name"><a href="<?php echo $this->getProductLink() ?>id/<?php echo $_review->getEntityPkValue() ?>"><?php echo $this->htmlEscape($_review->getName()) ?></a></h2></li>
        <li>
            <?php if($_review->getSum()): ?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo ( $_review->getSum() / $_review->getCount() ) ?>%;"></div>
                </div>
            <?php endif; ?><?php echo $this->helper('review')->getDetailHtml($_review->getDetail()) ?>
        </li>
        <li class="last"><a href="<?php echo $this->getReviewLink() ?>id/<?php echo $_review->getReviewId() ?>" class="nobr blacklink"><?php echo $this->__('View Details') ?></a></li>
    </ul>
    <?php endforeach; ?>
<?php else: ?>
    <p><?php echo $this->__('You have submitted no reviews.') ?></p>
<?php endif; ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>