<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getFeaturedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_basehelper = Mage::helper('softssbase');
?>
<?php if($_productCollection->count()): ?>
<div id="hp-products">
    <strong><?php echo $this->__('Featured Products'); ?></strong>
    <div class="carouselbuttons">
    <a class="buttons prev" href="#">left</a>
    <a class="buttons next" href="#">right</a>
    </div>
    <div class="viewport bottom_shadow">
        <ul class="overview">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php
            $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
            if(strlen($productName)>45){
                $productName = $_basehelper->cutStr($productName, 45).'...';
            }
        ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName;?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <div class="priceBubble">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <?php if($_product->isSaleable()): ?>
                <div class="cartBubble" onclick="addProduct('<?php echo $_product->getId() ?>',1)"></div>
                <div class="actions">
                   <?php echo $this->__('In stock - 24 + Free Ship'); ?>
                <?php else: ?>
                <div class="actions">
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
                </div>

            </li>
        <?php endforeach ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    $j(document).ready(function(){
        $j('#hp-products').tinycarousel({display: 5, duration: 1000});
    });
    //]]>
</script>
<?php endif; ?>