<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

<div id="hp-products">
    <a class="buttons prev" href="#">left</a>
    <div class="viewport">
        <ul class="overview">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="addProduct('<?php echo $_product->getId() ?>',1)"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <a class="buttons next" href="#">right</a>
</div>

<div id="overlay"></div>
<div id="ajax_add_item_container">
    <div class="ajax-container-head"><a onclick="hideOverlay()">close</a></div>
    <div id="ajax-cart-message"></div>
</div>

<script type="text/javascript">
    //<![CDATA[
    $j(document).ready(function(){
        $j('#hp-products').tinycarousel({display: 3, duration: 1000});
    });

    function addProduct(proudctID, quantity)
    {
        $j.ajax({
            url: '<?php echo Mage::getUrl('checkout/cart/addAjax'); ?>',
            data: 'product=' + proudctID + '&qty=' + quantity,
            type: 'GET',
            dataType: 'json',
            beforeSend: function() {
                var overlay = $j('#overlay').html('<img id="imgloading" src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" />').show();
            },
            success: function(response) {
                 $j('#ajax-cart-message').html(response.message);
                 $j('#ajax_add_item_container').fadeIn();
            },
            error: function(response) {
                alert(response.message);
                $j('#overlay').hide();
            }
        });
    }

    function hideOverlay(){
        $j('#overlay').fadeOut();
        $j('#ajax_add_item_container').fadeOut();
    }
    //]]>
</script>
<?php endif; ?>