<div id="onestepcheckout-login-form-div">
    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-contents">
            <div id="onestepcheckout-login-popup-contents-forgot" style="display: none;">
                <div class="login-right">
                    <h1><?php echo $this->__('Forgotten your password?'); ?></h1>
                    <p><?php echo $this->__('Enter your email below and we\'ll send you a new password by email.'); ?></p>
                </div>
                <div class="login-left">
                    <form id="onestepcheckout-forgot-form">

                        <div id="onestepcheckout-forgot-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                        <div id="onestepcheckout-forgot-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>
                        <div id="onestepcheckout-forgot-success" style="display: none;">
                            <?php echo $this->__('We have now sent you a new password to your email address. Click the link below to return to login.'); ?>
                        </div>

                         <ul id="onestepcheckout-forgot-table" class="form-list">

                            <li class="fields">
                                <div class="field">
                                    <label class="required" for="id_onestepcheckout_email"><em>*</em><?php echo $this->__('Email address'); ?></label>
                                    <div class="input-box">
                                        <input type="text" class="input-text required-entry validate-email" maxlength="255" title="<?php echo $this->__('Email address'); ?>" value="" name="onestepcheckout_email" id="id_onestepcheckout_email">
                                    </div>
                                </div>
                                <div class="button-div">
                                    <button id="onestepcheckout-forgot-button" class="medium orange onestepcheckout-button" type="button"><span><span><?php echo $this->__('Send password'); ?></span></span></button>
                                </div>                        
                            </li>
                        </ul>           
                    </form>
                   </div>              
                <p class="return-link"><a href="javascript:void(0);" id="onestepcheckout-return-login-link"><?php echo $this->__('Return to login'); ?></a></p>
                </div>
            </div>  
            <div id="onestepcheckout-login-popup-contents-login">
                <div class="login-right">
                    <h1><?php echo $this->__('Iam already a customer.'); ?></h1>
                    <p><?php echo $this->__('Please login with your email address and password.'); ?></p>
                </div>
                <div class="login-left">
                <form id="onestepcheckout-login-form">

                    <div id="onestepcheckout-login-loading" style="display: none;" class="loading-ajax-login">&nbsp;</div>
                    <div id="onestepcheckout-login-error" class="onestepcheckout-error" style="display: none;">&nbsp;</div>

                    <ul id="onestepcheckout-login-table" class="form-list">

                        <li class="fields">
                            <div class="field">
                                <label class="required" for="id_onestepcheckout_username"><em>*</em><?php echo $this->__('Email address'); ?></label>
                                <div class="input-box">
                                    <input type="text" class="input-text required-entry validate-email" maxlength="255" title="<?php echo $this->__('Email address'); ?>" value="" name="onestepcheckout_username" id="id_onestepcheckout_username">
                                </div>
                            </div>
                            <div class="field">
                                <label class="required" for="id_onestepcheckout_password"><em>*</em><?php echo $this->__('Password'); ?></label>
                                <div class="input-box">
                                    <input type="password" class="input-text required-entry" maxlength="255" title="<?php echo $this->__('Password'); ?>" value="" name="onestepcheckout_password" id="id_onestepcheckout_password">
                                </div>
                            </div>
                            <div class="button-div">
                                <button tabindex="102" class="medium orange onestepcheckout-button" id="onestepcheckout-login-button" type="button"><span><span><?php echo $this->__('Login'); ?></span></span></button>
                            </div>                         
                        </li>
                    </ul>
                </form>
                </div>
                <p class="forget-link"><a href="javascript:void(0);" id="onestepcheckout-forgot-password-link"><?php echo $this->__('Forgotten your password?'); ?></a></p>
            </div>       
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>

<script>
    
    var onestepcheckout_login_popup;
    var login_popup;
    Event.observe(window, 'load', function() {
        var options = {
            forgot_password_url: '<?php echo $this->getUrl('onestepcheckout/ajax/forgotPassword', array('_secure' => true)); ?>',
            login_url: '<?php echo $this->getUrl('onestepcheckout/ajax/login', array('_secure' => true)); ?>',
            translations: {
                invalid_email: '<?php echo $this->__('Please enter a valid email address'); ?>',
                email_not_found: '<?php echo $this->__('Please enter a registered email address.'); ?>'
            }
        };
        onestepcheckout_login_popup = new OneStepCheckoutLoginPopup(options);
        login_popup = onestepcheckout_login_popup;
    });
</script>
