<div class="footer-container">
    <div class="footer">
        <?php #echo $this->getChildHtml() ?>

        <div class="footer-column">
            <h3>Information</h3>
            <ul>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>">About Us</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Delivery Information</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Privacy Policy</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Terms & Conditions</a></li>
            </ul>
        </div>

        <div class="footer-column">
            <h3>Customer Service</h3>
            <ul>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Contact Us</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Returns</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>">Site Map</a></li>
            </ul>
        </div>

        <div class="footer-column">
            <h3>Extras</h3>
            <ul>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>">Discount Offers</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Technology Guide</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Coupon Email</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Apple Service Point</a></li>
            </ul>
        </div>

        <div class="footer-column">
            <h3>My Account</h3>
            <ul>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">My Account</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Order History</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Wish List</a></li>
                <li><a href="<?php echo $this->getUrl('aboutus') ?>" rel="nofollow">Newsletter</a></li>
            </ul>
        </div>

        <div class="footer-column contactDetails">
            <div class="footer-cards"><img src="<?php echo $this->getSkinUrl('images/cards.png') ?>" alt="paypal visa mastercard american express"/></div>
            Call us <span class="telnum">5154-877-233</span><br/>
            Email : info@softwaresuperstore.co.uk
        </div>
    </div>
    <div class="copyright"><?php echo $this->getCopyright() ?></div>
</div>
