<?php echo $this->getChildHtml('featured') ?>

<h1 class="homepage-softwaress">Software Superstore</h1>

<div>
    <div class="left">
      <?php echo $this->getChildHtml('home.catalog.category.menu') ?>
    </div>
    <div class="right homepage-lastest">
        <?php echo $this->getChildHtml('home.cat.games') ?>

        <!--<div class="latest-products">
            <?php echo $this->getChildHtml('home.catalog.product.new') ?>
        </div>-->
        <div id="home-page-social">
            <?php echo $this->getChildHtml('homepage-social') ?>
        </div>
    </div>
</div>