<div id="pagetoplinks-container">
    <div class="pagetoplinks">
        <div class="toplink">
            Home Software PACKAGES from &pound;450:
        </div>
        <div class="toplink">
            Business & Finance PACKAGES from &pound;750:
        </div>
        <div class="toplink">
            Creative Software PACKAGES from &pound;950:
        </div>
        <div class="toplink">
            other PACKAGES
        </div>
    </div>
</div>