<div id="pagetoplinks-container">
    <div class="pagetoplinks">
        <div class="toplink">
            Home Software PACKAGES &nbsp;&nbsp;<span class="black">from &pound;450:</span>
        </div>
        <div class="dotted-divider"></div>
        <div class="toplink">
            Business & Finance PACKAGES &nbsp;&nbsp;<span class="black">from &pound;750:</span>
        </div>
        <div class="dotted-divider"></div>
        <div class="toplink">
            Creative Software PACKAGES &nbsp;&nbsp;<span class="black">from &pound;950:</span>
        </div>
        <div class="dotted-divider"></div>
        <div class="toplink">
            other PACKAGES
        </div>
    </div>
</div>