<?php
$_items = $this->getReviewsCollection()->getItems();
$productRatingSummary = $this->getProduct()->getRatingSummary();
?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <div class="left">
        <div class="customer-ratings-count">
            <h2><?php echo $this->__('Average customer rating'); ?></h2>
            <span>
            <?php if ($productRatingSummary):?>
                <div class="rating-box">
                    <div class="rating" style="width:<?php echo $productRatingSummary->rating_summary ?>%"></div>
                </div>
            <?php endif;?>
            <?php echo count($_items) ?> <?php echo $this->__('customer reviews'); ?>
            </span>
        </div>

        <?php if (count($_items)):?>
            <h2><?php echo $this->__('Customer Reviews') ?></h2>
            <?php echo $this->getChildHtml('toolbar') ?>
            <dl>
            <?php foreach ($_items as $_review):?>
                <dt>
                    <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo ucfirst($this->htmlEscape($_review->getTitle())) ?></a> - <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?>
                    <small class="date"><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></small>
                </dt>
                <dd>
                    <?php $_votes = $_review->getRatingVotes(); ?>
                    <?php if (count($_votes)): ?>
                    <table class="ratings-table">
                        <col width="1" />
                        <col />
                        <tbody>
                            <?php foreach ($_votes as $_vote): ?>
                            <tr>
                                <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                                <td>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                    </div>
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <?php endif; ?>
                    <?php echo nl2br($this->htmlEscape($_review->getDetail())) ?>
                </dd>
            <?php endforeach; ?>
            </dl>
            <?php echo $this->getChildHtml('toolbar') ?>
        <?php endif;?>
    </div>

    <div class="right">
        <div id="customer-ratings-form" >
            <?php echo $this->getLayout()->createBlock('review/form')->setBlockId('product.review.form')->toHtml() ?>
        </div>
    </div>
</div>
