<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <p class="rating-links">
            <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
            <span class="separator">|</span>
            <a href="<?php echo $this->getProduct()->getProductUrl(); ?>#review-form" onclick="activateReviewTab()"><?php echo $this->__('Add Your Review') ?></a>
        </p>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><a href="<?php echo $this->getProduct()->getProductUrl(); ?>#review-form" onclick="activateReviewTab()"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[

document.observe('dom:loaded', function () {
    if(window.location.hash == '#review-form'){
	activateReviewTab();
    }

});

function activateReviewTab(){

    var tabs = $$('.product-tabs li');
    tabs.each(function(tab) {
	if(tab.hasClassName('active')){
	    tab.removeClassName('active');
	    $(tab.id+'_contents').hide();
	    $('product_tabs_reviews').addClassName('active');
	    $('product_tabs_reviews_contents').show();
	}
    });
}
//]]>
</script>