<?php
/**
 * @category  Devcores
 * @package   Devcores_Userlike
 * @author    Devcores <info@devcores.com>
 * @author    Sven Gebhardt <sven@devcores.com>
 * @copyright 2012 Devcores UG (haftungsbeschraenkt)
 * @link      http://devcores.com/
 */
?>

<?php if($this->isActive()): ?>
    <script src="https://s3-eu-west-1.amazonaws.com/userlike-cdn-widgets/<?php echo $this->getSecret(); ?>.js"></script>
<?php endif; ?>
