<?php
    $_cartQty = $this->getSummaryCount();
    if(!isset($_cartQty)) $_cartQty = 0;
?>
<div class="shoppingcartcontent">
    <div class="shoppingcart">Shopping Cart:</div> (
    <?php if ($_cartQty==1): ?>
        <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $_cartQty ?> item</a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $_cartQty ?> items</a>
    <?php endif ?>
)
<?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
    <?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>
<?php else : ?>
    <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
<?php endif; ?>
</div>