<?php
/**
 * Product list homepage template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_category = Mage::getModel('catalog/category')->load(4);
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products cat-home">
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
    <?php // Grid Mode ?>

    <?php $_collectionSize = 12 ?>
    <?php $_columnCount = 4; ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <?php $instock = $_product->isSaleable(); ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" <?php if(!$instock) echo 'class="imgoutofstock"'; ?> width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <div class="priceBubble">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <?php if($instock): ?>
                <div class="cartBubble" onclick="addProduct('<?php echo $_product->getId() ?>',1)"></div>
                <!--<div class="actions">
                    <?php echo $this->__('In stock - ').(int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
                </div>-->
                <?php else: ?>
                <div class="actions">
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                </div>
                <?php endif; ?>

            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
</div>
<?php endif; ?>