<?php
    $_helper = $this->helper('catalog/output');
?>
<?php if($this->getItemCollection()->getItems()): ?>
<div class="carousellist-label"><?php echo $this->__('You may also be interested<br/>in the following<br/>products') ?></div>
<div id="hp-latest-products">
    <div class="carouselbuttons">
    <a class="buttons prev" href="#">left</a>
    <a class="buttons next" href="#">right</a>
    </div>
    <div class="viewport">
        <ul class="overview">
        <?php $i=0; ?>
        <?php $this->resetItemsIterator() ?>
        <?php for($n = 0; $n<$this->getColumnCount(); $n++):?>
            <?php if($_product=$this->getIterableItem()): ?>
            <?php $instock = $_product->isSaleable(); ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <a href="<?php echo $_product->getUrlKey() ?>" title="<?php echo $_product->getName() ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" <?php if(!$instock) echo 'class="imgoutofstock"'; ?> width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <div class="priceBubble">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <?php if($$instock): ?>
                <div class="cartBubble" onclick="addProduct('<?php echo $_product->getId() ?>',1)"></div>
                <!--<div class="actions">
                    <?php echo $this->__('In stock - ').(int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
                </div>-->
                <?php else: ?>
                <div class="actions">
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                </div>
                <?php endif; ?>
            </li>
            <?php endif; ?>
        <?php endfor; ?>
        </ul>
    </div>
</div>

<script type="text/javascript">
    //<![CDATA[
    $j(document).ready(function(){
        $j('#hp-latest-products').tinycarousel({display: 1, duration: 1000});
    });
    //]]>
</script>
<?php endif; ?>