<?php
    $collection = $this->getCollection();
    $_helper = $this->helper('catalog/output');
    $_basehelper = Mage::helper('softssbase');
    $cartproduct = $this->getProduct();
?>
<div id="ajax-container-head"><a onclick="hideOverlay()">close</a></div>
<div id="ajax-cart-message"><?php echo $this->cart_message; ?></div>
<div id="ajax-product-view">
    <ul>
        <li><img src="<?php echo $this->helper('catalog/image')->init($cartproduct, 'small_image')->resize(80); ?>" width="80" height="80" alt="<?php echo $this->stripTags($this->getImageLabel($cartproduct, 'small_image'), null, true) ?>" /></li>
        <li><?php echo $_helper->productAttribute($cartproduct, $cartproduct->getName(), 'name');?></li>
        <li><?php echo $cartproduct->getPriceHtml($_product, true)  #$cartproduct->getPrice() ?></li>
    </ul>
</div>
<div id="ajax-container-links">
    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="hideOverlay()"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    <button type="button" title="<?php echo $this->__('View Cart') ?>" class="button btn-continue" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>')"><span><span><?php echo $this->__('View Cart') ?></span></span></button>
</div>
<?php if($collection->count()>0): ?>
<div id="ajax-container-realated-items">
    <a class="buttons prev" href="#">left</a>
    <div class="viewport">
        <ul class="overview">
        <?php $_collectionSize = $collection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($collection as $_product): ?>
            <?php
            $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
            if(strlen($productName)>45){
                $productName = $_basehelper->cutStr($productName, 45).'...';
            }
        ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName ?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <div class="priceBubble">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <div class="actions"><?php if(!$_product->isSaleable()): ?>In stock - <?php echo (int) Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?> + Free Ship
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>

            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <a class="buttons next" href="#">right</a>
</div>
<script type="text/javascript">
    //<![CDATA[
    $j('#ajax-container-realated-items').tinycarousel({display: 2, duration: 1000});
    //]]>
</script>
<?php endif; ?>