<?php
    $collection = $this->getCollection();
    $_helper = $this->helper('catalog/output');
    $_basehelper = Mage::helper('softssbase');
    $cartproduct = $this->getProduct();
?>
<div id="ajax-container-head" class="bottom_shadow">
    <div id="ajax-cart-message"><?php echo $this->cart_message; ?></div>
    <a onclick="hideOverlay()" class="close">X</a>
</div>
<div class="clear"></div>
<div id="ajax-product-view" class="bottom_shadow">
    <ul>
        <li><img src="<?php echo $this->helper('catalog/image')->init($cartproduct, 'small_image')->resize(76); ?>" width="76" height="76" alt="<?php echo $this->stripTags($this->getImageLabel($cartproduct, 'small_image'), null, true) ?>" /></li>
        <li class="txt">
            <?php echo $_helper->productAttribute($cartproduct, $cartproduct->getName(), 'name');?><br/>
            <span class="small"><?php echo $this->__('Article number');?>: <?php echo $cartproduct->getId();?></span>
        </li>
        <li class="txt">
            <?php echo Mage::helper('core')->currency($cartproduct->getFinalPrice(), true, false); ?><br/>
            <span class="small"><?php echo $this->__('Quantity'); ?>: <?php echo $this->quantity; ?></span>
        </li>
    </ul>
</div>
<div id="ajax-container-links">
    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue black" onclick="hideOverlay()"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
    <button type="button" title="<?php echo $this->__('View Cart') ?>" class="button btn-continue black" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getCartUrl() ?>')"><span><span><?php echo $this->__('View Cart') ?></span></span></button>
    <div class="right">
        <?php echo $this->getLayout()->createBlock('checkout/onepage_link')->setTemplate("checkout/onepage/link.phtml")->toHtml(); ?>
    </div>
</div>

<?php if($collection->count()>0): ?>
<div id="ajax-container-realated-items">
   <!--<div class="otherproducttxt"><?php echo $this->__('You may also be interested in:'); ?></div>-->
    <div class="carouselbuttons">
        <a class="buttons prev" href="#">left</a>
        <a class="buttons next" href="#">right</a>
    </div>
    <div class="viewport bottom_shadow">
        <ul class="overview">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $i=0; foreach ($collection as $_product): ?>
            <?php
            $productName = $_helper->productAttribute($_product, $_product->getName(), 'name');
            if(strlen($productName)>45){
                $productName = $_basehelper->cutStr($productName, 45).'...';
            }
        ?>
            <?php $instock = $_product->isSaleable(); ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $productName ?></a></h2>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(130); ?>" <?php if(!$instock) echo 'class="imgoutofstock"'; ?> width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>

                <div class="priceBubble">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>

                <div class="actions">
                    <?php if($instock): ?>
                    <?php #echo $this->__('In stock - ').(int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty(); ?>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                </div>

            </li>
        <?php endforeach ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    function initCarousel(){
        $j('#ajax-container-realated-items').tinycarousel({display: 1, duration: 1000});
    }
    //]]>
</script>
<?php endif; ?>