<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<ul class="accountlistheader">
    <li  class="ordernum"><?php echo $this->__('Order #') ?></li>
    <li class="date"><?php echo $this->__('Date') ?></li>
    <li class="shipto"><?php echo $this->__('Ship To') ?></li>
    <li class="ordertotal"><span class="nobr"><?php echo $this->__('Order Total') ?></li>
    <li class="status"><span class="nobr"><?php echo $this->__('Order Status') ?></span></li>
    <li class="last">&nbsp;</li>
</ul>

<?php $_odd = ''; ?>
<?php foreach ($_orders as $_order): ?>
<ul class="accountlist">
    <li class="ordernum"><?php echo $_order->getRealOrderId() ?></li>
    <li class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></li>
    <li class="shipto"><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></li>
    <li class="ordertotal"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></li>
    <li class="status"><em><?php echo $_order->getStatusLabel() ?></em></li>
    <li class="last">
        <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>" class="link-view"><?php echo $this->__('View Order') ?></a>
            <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
            <?php endif ?>
        </span>
    </li>
</ul>
<?php endforeach; ?>

<?php echo $this->getPagerHtml(); ?>

<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif ?>
