<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<?php $_order = $this->getOrder() ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
    <?php echo $this->getChildHtml('buttons') ?>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
<div class="order-info-box date">
    <h2><?php echo $this->__('Order Date'); ?></h2>
    <p>
        <?php echo $this->formatDate($_order->getCreatedAtStoreDate(), 'long') ?>
    </p>
</div>

<div class="order-info-box">
    <h2><?php echo $this->__('Payment Method') ?></h2>
    <p>
        <?php echo $this->getPaymentInfoHtml() ?>
    </p>
</div>

<div class="order-info-box last">
    <h2><?php echo $this->__('Billing Address') ?></h2>
    <p>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </p>
</div>

<?php if (!$_order->getIsVirtual()): ?>
<div class="order-info-box">
    <h2><?php echo $this->__('Shipping Method') ?></h2>
    <p>
    <?php if ($_order->getShippingDescription()): ?>
        <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
    <?php else: ?>
        <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
    <?php endif; ?>
    </p>
</div>
<div class="order-info-box last">
     <h2><?php echo $this->__('Shipping Address') ?></h2>
     <p>
         <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
     </p>
</div>
<?php endif; ?>
