<?php  $_order = $this->getOrder() ?>
<ul class="accountlistheader">
    <li class="productnamelong"><?php echo $this->__('Product Name') ?></li>
    <li class="sku"><?php echo $this->__('SKU') ?></li>
    <li class="price"><?php echo $this->__('Price') ?><li>
    <li class="qty"><?php echo $this->__('Qty') ?></li>
    <li class="last"><?php echo $this->__('Subtotal') ?></li>
</ul>
<?php $_items = $_order->getItemsCollection(); ?>
<?php $_index = 0; ?>
    <?php $_count = $_items->count(); ?>
<?php foreach ($_items as $_item): ?>
<?php if ($_item->getParentItem()) continue; ?>
    <?php echo $this->getItemHtml($_item) ?>

    <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item) && $_item->getGiftMessageId()): ?>
    <ul class="border<?php echo ($_index++ > $_count ?' last':'') ?>" id="order-item-gift-message-<?php echo $_item->getId() ?>" style="display:none;">
        <?php $_giftMessage=$this->helper('giftmessage/message')->getGiftMessageForEntity($_item); ?>
        <td class="gift-message-row" colspan="7">
            <a href="#" title="<?php echo $this->__('Close') ?>" onclick="return giftMessageToogle('<?php echo $_item->getId() ?>');" class="btn-close"><?php echo $this->__('Close') ?></a>
            <dl class="gift-message">
                <dt><strong><?php echo $this->__('From:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?></dt>
                <dt><strong><?php echo $this->__('To:') ?></strong> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?></dt>
                <dd><?php echo $this->helper('giftmessage/message')->getEscapedGiftMessage($_item) ?></dd>
            </dl>
        </td>
    </ul>

    <?php endif ?>
<?php endforeach; ?>

<?php echo $this->getChildHtml('order_totals') ?>
