<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>

    <ul class="accountlistheader">
        <li id="ordernr" class="ordernum"><?php echo $this->__('Order #') ?></li>
        <li id="date" class="date"><?php echo $this->__('Date') ?></li>
        <li id="ship-to" class="productname"><?php echo $this->__('Ship To') ?></li>
        <li id="amount" class="ordertotal"><span class="nobr"><?php echo $this->__('Order Total') ?></span></li>
        <li class="status"><?php echo $this->__('Status') ?></li>
        <li class="last">&nbsp;</li>
    </ul>

    <?php foreach ($_orders as $_order): ?>
        <ul class="accountlist">
            <li class="ordernum"><strong><?php echo $_order->getRealOrderId() ?></strong></li>
            <li class="date"><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></li>
            <li class="productname"><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></li>
            <li class="ordertotal"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></li>
            <li class="status"><?php echo $_order->getStatusLabel() ?></li>
            <li class="last">
                <span class="nobr"><a class="link-view" href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                        <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                    <?php endif ?>
                </span>
            </li>
    </li>
        </ul>
    <?php endforeach; ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>
