<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
    <ul class="<?php echo $_code?> accountlist">
        <li class="productnamelong">&nbsp;</li>
        <li class="sku">&nbsp;</li>
        <li class="price">&nbsp;</li>
        <li <?php echo $this->getLabelProperties()?> class="qty">
            <?php if ($_total->getSulong()):?>
            <sulong><?php echo $this->escapeHtml($_total->getLabel());?></sulong>
            <?php else:?>
            <?php echo $this->escapeHtml($_total->getLabel());?>
            <?php endif?>
        </li>
        <li <?php echo $this->getValueProperties()?> class="last">
            <?php if ($_total->getSulong()):?>
            <sulong><?php echo $this->formatValue($_total) ?></sulong>
            <?php else:?>
            <?php echo $this->formatValue($_total) ?>
            <?php endif?>
        </li>
    </ul>
    <?php endif?>
<?php endforeach?>
