<?php
/**
 * Product description template
 *
 * @see Mage_Catalog_Block_Product_View_Description
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $_description = $_product->getDescription(); ?>
<?php $_cat_helper = Mage::helper('softsscatalog'); ?>
<?php if ($_description): ?>
    <div class="left">
        <div class="std">
            <?php echo $this->helper('catalog/output')->productAttribute($_product, $_description, 'description') ?>
        </div>
    </div>
    <div class="right">
        <div class="socialinks">

            <div class="fb-like" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false" data-font="verdana"></div>

            <div class="g-plusone" data-size="tall" data-annotation="inline" data-width="120"></div>

            <div class="btn_twitter"><a href="https://twitter.com/share" class="twitter-share-button" data-via="twitterapi" data-lang="en">Tweet</a></div>
        </div>
        <ul class="product-specs">
            <?php foreach($_product->getAttributes() as $attribute):?>
                <?php if ($attribute->getIsVisibleOnFront()) : ?>
                <?php $attrValue = $_cat_helper->getProductAttributeValue($_product, $attribute); ?>
                    <?php if ($attrValue !=  'N/A'  && !($attrValue ==  'No' && $attribute->getCode() != 'softss_backup_cd_available')) : ?>
                    <li><label><?php echo $this->__($attribute->getStoreLabel()) ?></label><span><?php echo $_cat_helper->getProductAttributeValue($_product, $attribute) ?></span></li>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript">
  window.___gcfg = {lang: 'en-GB'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


<?php endif; ?>

